# docker-compose.yml
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '53603:53603'
      - '80:80'
    env_file:
      - database.env

volumes:
  database-data:
